### ISSUE TITLE
Adding prometheus instrumentation package is resulting in some requests taking a long amount of time

### ISSUE THREAD

**Issue by rileyhun** [jeremyjordan/ml-monitoring#9]
Hello again @jeremyjordan,

We are trying to decrease the latency of our BERT model prediction service that is deployed using FastAPI. The predictions are called through the `/predict` endpoint. We looked into the tracing and found one of the bottlenecks is the `prometheus-fastapi-instrumentator`. About 1% of the requests do `timeout` because they exceed 10s.  

We also discovered that some metrics are not getting reported on 4 requests/second. Some requests took 30-50 seconds, with the `starlette/fastapi` taking long times. So it seems that under high usage, the `/metrics` endpoint doesn't get enough resources, and hence all `/metrics` requests wait for some time and fail eventually. So having separate container for metrics could help. Or if possible to have metrics delayed/paused under high load. Any insight/guidance would be much appreciated. 

<img width="1517" alt="Screen Shot 2021-12-03 at 6 37 51 PM" src="https://user-images.githubusercontent.com/20649466/144699048-29cc2700-e0e1-42a4-94b9-5b231e8b3c05.png">
<img width="1490" alt="Screen Shot 2021-12-03 at 6 37 38 PM" src="https://user-images.githubusercontent.com/20649466/144699055-0bb5d1f4-57b0-4884-8565-dc940e286b4b.png">
<img width="1533" alt="Screen Shot 2021-12-03 at 7 59 40 PM" src="https://user-images.githubusercontent.com/20649466/144699144-e86ecbd6-1489-432c-b790-29773d82b66b.png">

**Comment by jeremyjordan** [comment]
Hi there!

> We looked into the tracing and found one of the bottlenecks is the prometheus-fastapi-instrumentator.

This is interesting, and I would definitely recommend raising an issue in the [Github repository](https://github.com/trallnag/prometheus-fastapi-instrumentator) for that library so the maintainer is aware of the issues. However, it's not clear whether the performance issue is with `prometheus-fastapi-instrumentator` or the underlying `prometheus_client` library. The former is really just a convenient and lightweight wrapper around the latter.

> So it seems that under high usage, the /metrics endpoint doesn't get enough resources, and hence all /metrics requests wait for some time and fail eventually. So having separate container for metrics could help.

According to the [docs](https://trallnag.github.io/prometheus-fastapi-instrumentator/), you should be able to instrument your main application and then expose a second application which returns the metrics. However, both of these server processes would be running in the same container.

Good luck digging into this!

**Comment by rileyhun** [comment]
Thanks @jeremyjordan. I'll raise an issue on the `prometheus-fastapi-instrumentator` github repository, but doesn't look like the maintainers are particularly active, but worth a try. 

Would it help to increase the number of `gunicorn` workers and then use `prometheus_client`[ multiprocess mode](https://github.com/prometheus/client_python/#multiprocess-mode-eg-gunicorn)?

**Comment by jeremyjordan** [comment]
Yes, I'd recommend reading through https://fastapi.tiangolo.com/deployment/server-workers/ if you haven't already. The FastAPI docs are great 🎉
